# 应用名称
spring:
  application:
    name: rabbitmq
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
      virtualHost: /kavito
      #有关AmqpTemplate的配置
      template:
        #失败重试
        retry:
          #开启失败重试
          enabled: true
          #第一次重试的间隔时长
          initial-interval: 10000ms
          #最长重试间隔，超过这个间隔将不再重试
          max-interval: 300000ms
          #下次重试间隔的倍数，此处是2即下次重试间隔是上次的2倍
          multiplier: 2
          #缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
        exchange: topic.exchange
      #生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试
      publisher-confirms: true



server:
  port: 10086